### ISSUE TITLE
Crash back to Title Screen with Version 1.1.0

### ISSUE THREAD

**Issue by Dream-Master** [Drethic/QuestBook#8] opened 2016-05-01 11:53 UTC
When importing a decent amount of Quests for no reason the Game close and I am back on the title screen. I cant join the game anymore. Seems the Book bug me out because it happened too if no Quests are saved (no DefaultQuests.jason file)

Ther is no crash log only the fml log i post here.

full fml log:
https://gist.github.com/Dream-Master/6076e110aad8a5527dd8e0ee1d078a9c

error 1:
https://gist.github.com/Dream-Master/91d2a81b0e90aabce74b885419e3e560

error 2:
https://gist.github.com/Dream-Master/b6dd5df6714b84a0d656baf57d2228c7

There are more errors i just pick two out of the log.

Testing now with 1.0.1 if happend too.

**Comment by Dream-Master** [comment] 2016-05-01 12:07
crash with 1.0.1 too. No lue why it works before fine without any error.

**Comment by Drethic** [comment] 2016-05-01 12:40
Did you also update the Better Questing mod when you updated Quest Book?

A lot of the errors I see in your log looks to be during imports.  I'm going to open a ticket with the Better Question author to see if he can help.

**Comment by Drehverschluss** [comment] 2016-05-01 13:17
Hello. im a guy who trying to help Dreammaster finding a solution.

Anyways yea the error are comming after we are trying to import a .json file wich is exported from HQM.

**Comment by Funwayguy** [comment] 2016-05-01 13:49
Can you include the json file you're trying to import?

**Comment by Dream-Master** [comment] 2016-05-01 13:56
Sure can do when I am back home

**Comment by Funwayguy** [comment] 2016-05-01 13:58
Looking into the error more, it seems to show that whatever you imported caused some sort of corruption resulting in a network packet with null data

**Comment by Drehverschluss** [comment] 2016-05-01 14:10
https://dl.dropboxusercontent.com/u/39281853/Server/BeesQuests.json

Thats the .json we are trying to import.

I saw that some quest names have a ":" .....isnt that causing errors before?

**Comment by Funwayguy** [comment] 2016-05-01 14:14
That isn't a HQM json file and won't work with the HQM importer

**Comment by Drehverschluss** [comment] 2016-05-01 14:23
hmm ok than we need to whait for DreamMaster

**Comment by Dream-Master** [comment] 2016-05-01 14:40
Yes I know it is a converted file.
After I can't load new files I try to export chapter by chapter and add them back. It don't work too.
So the data can't be corrupt because import this chapter alone without the others works with no errors.

**Comment by Dream-Master** [comment] 2016-05-01 14:41
https://gist.github.com/Dream-Master/f5c7e8d7be84a1d27dd2d02eb501c52a#file-how-to-bee

this is the exported json file from HQM.

**Comment by Dream-Master** [comment] 2016-05-01 14:44
But all other new files I try to adding don't work too.

Here the folder with HQM files and Better Questing files.

https://www.dropbox.com/sh/zp1d9frmc7qvspo/AACHiUBcySXY2gjpxwg3MZMva?dl=0

**Comment by Dream-Master** [comment] 2016-05-01 20:50
@Drethic 
@Funwayguy 

I find out was is maybe the Problem. In one Quest Line we adding Lore Tags. If I add this Chapter to the other Quests the Game closing to Title. Are Lore Tags not allowed or not yet supported?

**Comment by Dream-Master** [comment] 2016-05-01 21:34
I remove the Lore tags and it crash too. Have to look if only this chapter crash or other too.

**Comment by Dream-Master** [comment] 2016-05-01 22:01
@Drethic 
@Funwayguy

Ok other chapters crashing too. If I load all chapters separate and not combine them all works fine. It seems for me if you load to much chapters the game crash to Title screen. Can it be happened that the file got to big? is it possible to have more json files mean have all chapters separate as files but work together (means Chapter 2 need Quest out of Chapter 1)
hope you can help me here Guys.

**Comment by Funwayguy** [comment] 2016-05-02 01:41
I tried batch importing those HQM files and I can confirm the same error does occur in my developer workspace. I can start debugging where exactly the error occurs now and why however due to some University work I have to sort out in the next week or two I might not be able to push out a new update right now.

**Comment by Dream-Master** [comment] 2016-05-02 11:11
Ok Thanks. Will wait for a new Version then.

**Comment by Funwayguy** [comment] 2016-05-09 11:20
Just an update on this issue. I have found the exact cause. Seems Forge doesn't automatically break up network packets when they are too large to send causing data to be lost during sync and corrupting the client side database. I'm working on a way to fix this but it's proving difficult.

**Comment by Dream-Master** [comment] 2016-05-09 13:53
Ok Thanks. I hope you find a way. Let me know when i can test some stuff.

**Comment by Dream-Master** [comment] 2016-05-09 13:54
Btw is it possible to break down the one big file in smaller files? Mean maybe in chapter files?
So each chapter get a own json files to keep it small.

**Comment by Funwayguy** [comment] 2016-05-12 08:34
Update 1: This has been half fixed now. The mod will no longer crash from the quest database size overloading the packets but I still need to update the expansion importers to support it.

Update 2: Tested importing your massive database file with the new importers (unreleased) and everything went smoothly! I still need to update a bunch of other things before release but you'll be glad to know it works.

**Comment by Dream-Master** [comment] 2016-05-12 14:08
I am glad to hear this. So I can hopefully using the Quests soon. Thanks.

**Comment by Dream-Master** [comment] 2016-05-12 17:37
That mean i can have larger Json files without any crash but cant import new stuff now right?

**Comment by Drethic** [comment] 2016-05-17 01:52
@Funwayguy has closed the source issue (Funwayguy/BetterQuesting#26) which closes this issue.

**Closed as completed by Drethic** 2016-05-17 01:52 UTC

**Comment by Dream-Master** [comment] 2016-05-17 09:59
yes works fine thanks.
